[project]
name = "injectr-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "injector>=0.22.0",
]

[dependency-groups]
dev = [
    "coverage>=7.6.4",
    "pytest>=8.3.3",
    "ruff>=0.7.2",
]
